---
- name: Configure the PackageCloud APT key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Configure the Grafana APT repository
  apt_repository: repo="deb https://packagecloud.io/grafana/stable/debian/ wheezy main"
                  state=present

- name: Install Grafana
  apt: pkg=grafana={{ grafana_version }} state=present

- name: Configure Grafana
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini
  notify:
    - Restart Grafana

- name: Enable Grafana service
  service: name=grafana-server enabled=yes state=started
