---
- hosts: all

  vars:
    java_version: "7u79-*"
    collectd_load_plugins:
      - cpu
      - df
      - disk
      - interface
      - memory
      - write_graphite
    apache_port: 8080

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.graphite" }
    - { role: "azavea.grafana" }

  tasks:
    - name: Configure Collectd plugins
      template: src=templates/{{ item }}.conf.j2 dest=/etc/collectd/collectd.conf.d/{{ item }}.conf
      with_items:
        - df
        - write_graphite
      notify:
        - Restart Collectd
